// GENERATED by tools/simtest `balance tune` - do not edit by hand; rerun the lab after any kit change (docs/BALANCE.md).
namespace ZU.Sim.Data
{
    public static partial class Balance
    {
        static readonly (string id, double power)[] SHIPPED =
        {
            ("tenkai", 0.83),
            ("mirei", 0.7),
            ("kaien", 1.013),
            ("raijin", 1.15),
            ("gorgoth", 1.15),
            ("nocturne", 1.15),
            ("hex", 1.07),
            ("kagemaru", 0.923),
            ("enra", 1.15),
            ("gantetsu", 0.718),
            ("hibiki", 0.821),
            ("tomoe", 0.898),
            ("hayate", 0.7),
            ("seiran", 0.914),
        };
    }
}
