// GENERATED by tools/simtest `balance tune` - do not edit by hand; rerun the lab after any kit change (docs/BALANCE.md).
namespace ZU.Sim.Data
{
    public static partial class Balance
    {
        static readonly (string id, double power, double taken)[] SHIPPED =
        {
            ("tenkai", 1.129, 1),
            ("mirei", 0.85, 1.5),
            ("kaien", 0.876, 1),
            ("raijin", 1.6, 0.5),
            ("yuzu", 1, 1.5),
            ("gorgoth", 1.583, 1),
            ("nocturne", 1.445, 1),
            ("hex", 0.85, 1.157),
            ("kagemaru", 1.6, 1),
            ("enra", 1.6, 0.5),
            ("gantetsu", 0.917, 1.11),
            ("hibiki", 0.85, 1.096),
            ("tomoe", 0.979, 1),
            ("hayate", 1.132, 1),
            ("seiran", 1.6, 0.921),
        };
    }
}
